### ISSUE TITLE
Youtube API keys not working?

### ISSUE THREAD

**Issue by NonklyFriend** [matthieugrieger/mumbledj#122] opened 2016-02-13 18:58 UTC
"MumbleDJ does not have a valid YouTube API key."

The bot is being set up on a VPS, it worked before, We've tried server API keys and bowser API keys. The bot can connect to the mumble server without a issue, 

The youtube -dl works, but the bot doesn't work. Can anyone help us out here?

**Comment by matthieugrieger** [comment] 2016-02-14 04:36
Hi there!

Can you show me what you get as a response when you put this in your web browser?

```
https://www.googleapis.com/youtube/v3/videos?part=snippet,contentDetails&id=[ANY_YOUTUBE_ID_HERE]&key=[YOUR_API_KEY_HERE]
```

Make sure that you replace the strings within the brackets with the appropriate data, and also be sure to hide your API key if it shows up anywhere in the request response.

**Comment by joviniko** [comment] 2016-02-14 17:45
the problem seems to be, that in https://github.com/matthieugrieger/mumbledj/blob/master/youtube_dl.go#L59 the program tries to download always a m4a sound file. 

but many youtube videos don't have a m4a file.

**Comment by matthieugrieger** [comment] 2016-02-14 17:47
Ah, I see. Try out the newest release. It should be fixed. :)

**Comment by joviniko** [comment] 2016-02-14 17:53
newest release of youtube-dl?

i already have the newest one (2016-02-13)

what i have done, is changed the line to 

`cmd := exec.Command("youtube-dl", "--verbose", "--no-mtime", "--output", fmt.Sprintf("%s/.mumbledj/songs/%s", dj.homeDir, dl.Filename()), "--format", "bestaudio", "--prefer-ffmpeg", dl.url)`

so it downloads the best audio file and i just save it as a .m4a, doesn't matter for ffmpeg playback

**Comment by matthieugrieger** [comment] 2016-02-14 18:36
Sorry, I meant the newest version of MumbleDJ. Do a `git pull` and recompile.

**Comment by Deathus** [comment] 2016-02-14 19:26
Hello, I'm NonklyFriend's partner in crime :).  Following the advise above: Use v2.8.14, I can not seem to compile and get an executable that is v2.8.14.

What I have done:
1. Take existing local git repo and git pull -> "Already up-to-date"
2. Check git logs -> same
3. make clean -> make -> make install -> ./mumbledj -> !version -> v2.8.13
4. rm -r *
5. git clone https://github.com/matthieugrieger/mumbledj.git
6. git pull -> "Already up-to-date"
7. Check git logs -> same
8. make -> make install -> ./mumbledj -> !version -> v2.8.13
9. rm -r *
10. wget https://github.com/matthieugrieger/mumbledj/archive/2.8.14.tar.gz
11. tar -zxvf 2.18.14.tar.gz -> cd mumbledj-2.8.14
12. make -> make install -> ./mumbledj -> !version -> v2.8.13

And I am still having the same problems as the OP has stated.

**Comment by matthieugrieger** [comment] 2016-02-15 03:59
Sorry, I believe I simply forgot to update the version number in the code. Although I did not make any changes in the last update related to this issue, can you please try updating and verify that you are still having the issue?

**Comment by Deathus** [comment] 2016-02-15 12:18
I updated to v2.8.15. I am still having the issue of "MumbleDJ does not have a valid YouTube API key.". I tried using two different keys one of them was a fresh key.

**Comment by matthieugrieger** [comment] 2016-02-15 17:24
@Deathus, can you tell me what response you get if you put the API request from my first comment in your browser?

**Comment by Deathus** [comment] 2016-02-15 22:59
```
{
    "kind": "youtube#videoListResponse",
    "etag": "\"DsOZ7qVJA4mxdTxZeNzis6uE6ck/ZDiIGfaGdlaLOyRRhHv2ioolO-4\"",
    "pageInfo": {
        "totalResults": 0,
        "resultsPerPage": 0
    },
    "items": []
}
```
Used a project id and a server key.

**Comment by matthieugrieger** [comment] 2016-02-15 23:28
Can you tell me what YouTube ID you used?

Also, do you have any IP addresses listed in your API configuration on Google's website?

**Comment by Deathus** [comment] 2016-02-15 23:59
id: digitalocean-1219
Not for the key I used above.

**Comment by matthieugrieger** [comment] 2016-02-16 04:14
The ID for the API request should be an ID to a YouTube video, not a DigitalOcean ID. Sorry if I was unclear. Let me know what response you get.

**Comment by Deathus** [comment] 2016-02-16 04:57
```
{
 "kind": "youtube#videoListResponse",
 "etag": "\"DsOZ7qVJA4mxdTxZeNzis6uE6ck/ajlzOcCEd9G87ocnM7zkeJHZVro\"",
 "pageInfo": {
  "totalResults": 1,
  "resultsPerPage": 1
 },
 "items": [
  {
   "kind": "youtube#video",
   "etag": "\"DsOZ7qVJA4mxdTxZeNzis6uE6ck/PLlAVfhuxutKl2TGf6YQu3TK5Xg\"",
   "id": "GQQMLE4FuIQ",
   "snippet": {
    "publishedAt": "2016-02-15T13:59:52.000Z",
    "channelId": "UCZGYJFUizSax-yElQaFDp5Q",
    "title": "Star Wars: Episode VIII Production Announcement",
    "description": "Cameras roll for the next chapter of the Star Wars saga, written and directed by Rian Johnson. \n\nVisit Star Wars at http://www.starwars.com\nSubscribe to Star Wars on YouTube at http://www.youtube.com/starwars\nLike Star Wars on Facebook at http://www.facebook.com/starwars\nFollow Star Wars on Twitter at http://www.twitter.com/starwars\nFollow Star Wars on Instagram at http://www.instagram.com/starwars\nFollow Star Wars on Tumblr at http://starwars.tumblr.com/",
    "thumbnails": {
     "default": {
      "url": "https://i.ytimg.com/vi/GQQMLE4FuIQ/default.jpg",
      "width": 120,
      "height": 90
     },
     "medium": {
      "url": "https://i.ytimg.com/vi/GQQMLE4FuIQ/mqdefault.jpg",
      "width": 320,
      "height": 180
     },
     "high": {
      "url": "https://i.ytimg.com/vi/GQQMLE4FuIQ/hqdefault.jpg",
      "width": 480,
      "height": 360
     },
     "standard": {
      "url": "https://i.ytimg.com/vi/GQQMLE4FuIQ/sddefault.jpg",
      "width": 640,
      "height": 480
     },
     "maxres": {
      "url": "https://i.ytimg.com/vi/GQQMLE4FuIQ/maxresdefault.jpg",
      "width": 1280,
      "height": 720
     }
    },
    "channelTitle": "Star Wars",
    "tags": [
     "Star Wars",
     "Episode VIII"
    ],
    "categoryId": "24",
    "liveBroadcastContent": "none",
    "localized": {
     "title": "Star Wars: Episode VIII Production Announcement",
     "description": "Cameras roll for the next chapter of the Star Wars saga, written and directed by Rian Johnson. \n\nVisit Star Wars at http://www.starwars.com\nSubscribe to Star Wars on YouTube at http://www.youtube.com/starwars\nLike Star Wars on Facebook at http://www.facebook.com/starwars\nFollow Star Wars on Twitter at http://www.twitter.com/starwars\nFollow Star Wars on Instagram at http://www.instagram.com/starwars\nFollow Star Wars on Tumblr at http://starwars.tumblr.com/"
    }
   },
   "contentDetails": {
    "duration": "PT35S",
    "dimension": "2d",
    "definition": "hd",
    "caption": "false",
    "licensedContent": true
   }
  }
 ]
}
```
ID: GQQMLE4FuIQ
key: Same one I used last time.

**Comment by matthieugrieger** [comment] 2016-02-16 07:05
Hmmm.. I'm a bit stumped as to what the problem is then. If you get this kind of response when using the bot you should not be receiving the invalid API key error.

Are you sure that your API key was correctly copied into the configuration file?

**Comment by Deathus** [comment] 2016-02-16 23:24
Solved it. I was running into two simple problems (can't believe it took me this long to figure them out).

Problem 1:
I run the bot in a user account (userB) without sudo, su, or root privileges, and I use another account (userA) with privileges to make/make install/make clean/etc. Anyway, the /home/userB/.mumbledj/* files were either not being updated to reflect */mumbledj/config.gcfg changes, environment variable changes, or permission changes (files being created with root ownership for instance).

Problem 2:
I had the youtube and soundcloud Api keys both listed in the /etc/environment file as well as the */mumbldj/config.gcfg file. So when I would run make install, the make command would copy the keys twice (youtube = "KeyKey", soundcloud = "KeyKey") into the /home/userB/.mumbledj/config/mumbledj.gcfg file.

**Comment by matthieugrieger** [comment] 2016-02-17 02:17
Awesome, glad you figured it out!

**Closed by matthieugrieger** 2016-02-17 02:17 UTC
Labels: question
