### ISSUE TITLE
While attempting "make install," I receive this error:

### ISSUE THREAD

**Issue by mbt15** [matthieugrieger/mumbledj#52] opened 2015-03-26 02:39 UTC
=> Done!
goop go build .
user@ubuntu:~/dj$ make install
mkdir -p ~/.mumbledj/config
mkdir -p ~/.mumbledj/songs
if [ -a ~/.mumbledj/config/mumbledj.gcfg ]; then mv ~/.mumbledj/config/mumbledj.gcfg ~/.mumbledj/config/mumbledj_backup.gcfg; fi;
/bin/sh: 1: [: -a: unexpected operator
cp -u mumbledj.gcfg ~/.mumbledj/config/mumbledj.gcfg
if [ -d ~/bin ]; then cp -f mumbledj ~/bin/mumbledj; else sudo cp -f mumbledj /usr/local/bin/mumbledj; fi;
cp: cannot stat ‘mumbledj’: No such file or directory
make: *** [install] Error 1

**Comment by matthieugrieger** [comment] 2015-03-26 04:25
Can you verify that there is a `mumbledj` executable in your directory?

**Comment by rrelance** [comment] 2015-03-26 15:16
Hello, I also have this exact same problem when trying to execute "sudo make install"
Looking at my directory after executing "make", there is an executable named "mumbledj-2.6.7"

**Comment by matthieugrieger** [comment] 2015-03-26 16:37
@rrelance Ah, interesting.. I've never had it add the version number to its filename before.

It should be pretty easy to fix. I'll push one out as soon as I can.

**Comment by rrelance** [comment] 2015-03-26 17:12
Awesome. It seems like renaming the executable to "mumbledj" works out, but I'm not sure if it installed properly.  When using "sudo make install" after renaming, bash hangs but it looks like it completed, since mumbledj was installed to the correct directory, and I was able to launch your program through "mumbledj -(args followed)".

Although, a separate issue has come up. When using the bot to play music VIA YouTube, the audio would cut out every so often for a split second, and would continue.

In terms of describing this "cutting out", the mumble icon stops lighting up, and when the audio resumes, it kind of "fast forwards" from where it cut off and where it should be currently.

My setup is as follows:
Windows Server 2012
>VirtualBox
>>Lubuntu 14.10

I don't think its a resource issue as looking at Task Manager (inside Lubuntu) only 5% CPU is utilized,and 20% of memory is being used.

**Comment by matthieugrieger** [comment] 2015-03-26 17:38
@rrelance: Alright, I just pushed an update that should fix the `make install` problem. Please try it out and let me know if there are any issues.

A few questions to diagnose your audio cutting problem:
**1)** What do you see under the heading "Audio bandwidth" in Server -> Information? This is found in your Mumble client.
**2)** Are you running the bot on the same server you are running your Mumble server on? I've only ever run the bot on the same server as my Mumble server, so there is a possibility that some audio issues occur when running them on separate machines.

**Comment by rrelance** [comment] 2015-03-26 18:00
@matthieugrieger:
The following is displayed under "Audio bandwidth"
Maximum 110.8 kbits/s
Current 54.8 kbits/s
Codec: Opus

I am not running the bot on the same server my Mumble server is on. My Mumble server is hosted by Cleanvoice and the bot is running on my home server.

Although.. the idea just came to mind, that maybe my issue is caused by my laughable 3mbps/s upload speed (will be receiving an upgrade soon fortunately)? When talking on my Windows based Mumble client, my voice is a steady stream. Perhaps streaming YouTube music requires much higher bandwidth than talking.

Is there a way to change/limit the bandwidth used by MumbleDJ?

**Comment by matthieugrieger** [comment] 2015-03-26 18:08
@rrelance:
Yeah, your upload speed may have something to do with it. The only way that you can change the bandwidth for MumbleDJ (currently) is to change the maximum bandwidth for all users on your server, as explained [here](http://wiki.mumble.info/wiki/Murmur.ini#bandwidth). MumbleDJ should adapt to the changes made to bandwidth limits.

**Comment by rrelance** [comment] 2015-03-26 18:24
@matthieugrieger:
I took a look at youtube-dl arguments , and I found some settings relating to bitrate (mainly --audio-quality QUALITY under POST PROCESSING and  -f, --format FORMAT under VIDEO FORMAT OPTIONS), although I'm not entirely sure if changing those settings would help lower the bandwidth required from your bot or not.

Would either of these arguments help?

**Comment by matthieugrieger** [comment] 2015-03-26 19:32
@rrelance:
I'm not sure if those would help, but you're welcome to try it. If I had to guess I don't think it would do anything, since `gumble_ffmpeg` transcodes all audio with a fixed bitrate (48000Hz).

**Comment by mbt15** [comment] 2015-03-26 20:38
Updated to latest version.  Receiving new error code on make:

http://pastebin.com/hYDNCqk4

**Comment by mbt15** [comment] 2015-03-26 20:54
And this:

http://pastebin.com/sq5UCNKx

**Comment by matthieugrieger** [comment] 2015-03-26 20:56
@mbt15:
I didn't change anything related to `go build` in the newest update, so it is unrelated to the newest changes. What version of Go are you using?

**Comment by mbt15** [comment] 2015-03-26 20:58
On "go version":

go version xgcc (Ubuntu 4.9.1-0ubuntu1) 4.9.1 linux/amd64

**Comment by matthieugrieger** [comment] 2015-03-26 21:45
@mbt15:
Ah, looks like you're using something like `gccgo`. This project wasn't specifically written/tested for compatibility with `gccgo`, so unfortunately I won't be much help on this issue.

**Comment by mbt15** [comment] 2015-03-26 22:19
My bad, I switched over to regular go and it worked.  Sorry for the problems!

**Comment by mbt15** [comment] 2015-03-26 22:23
Shoot - now I am receiving this error on "make":

http://pastebin.com/BVd0cpQB

**Comment by rrelance** [comment] 2015-03-26 22:29
@mbt15 
If you look above, this is the same problem that OP and I had. Check your directory if there is an executable in it (might be named mumbledj(version#), although this is supposed to be fixed in the newest version). If there exists an executable named other than mumbledj, rename it to mumbledj and run make install again (might need to use sudo)

**Comment by mbt15** [comment] 2015-03-26 22:33
All good!

**Closed** 2015-03-27 00:34 UTC
Labels: setup help
