### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by caindrac** [matthieugrieger/mumbledj#169] opened 2016-07-11 00:12 UTC
#### Before submitting this issue, please acknowledge that you have done the following:
- [x] I've at least skimmed through the [README](https://github.com/matthieugrieger/mumbledj/blob/master/README.md)
- [x] I have checked that I am running the latest version of MumbleDJ (use `mumbledj --version` when starting the bot or use the MumbleDJ version command in Mumble)
- [x] I have [searched through the existing issues](https://github.com/matthieugrieger/mumbledj/issues) to see if my issue has been answered already

---

#### What type of issue is this?
- [x] Bug report (encountered problems with MumbleDJ)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other:

---

#### Log output of bot with `--debug` flag (likely only for bug reports):
```
panic: runtime error: slice bounds out of range

goroutine 14 [running]:
panic(0xa09860, 0xc82000e080)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/matthieugrieger/mumbledj/vendor/github.com/layeh/gumble/gumble.(*Client).handleUDPTunnel(0xc82050c600, 0xc820484e60, 0x6d, 0x95, 0x0, 0x0)
        /home/caindrac/work/src/github.com/matthieugrieger/mumbledj/vendor/github.com/layeh/gumble/gumble/handlers.go:138 +0xb7f
github.com/matthieugrieger/mumbledj/vendor/github.com/layeh/gumble/gumble.(*Client).readRoutine(0xc82050c600)
        /home/caindrac/work/src/github.com/matthieugrieger/mumbledj/vendor/github.com/layeh/gumble/gumble/client.go:225 +0x1de
created by github.com/matthieugrieger/mumbledj/vendor/github.com/layeh/gumble/gumble.DialWithDialer
        /home/caindrac/work/src/github.com/matthieugrieger/mumbledj/vendor/github.com/layeh/gumble/gumble/client.go:113 +0x3e4
```
---

#### Description of your issue:

Just crashes with this panic after a few min of playing.

**Comment by matthieugrieger** [comment] 2016-07-11 01:56
@bontibon: Looks like this might be an issue related to `gumble`.

**Comment by bontibon** [comment] 2016-07-11 15:42
> Just crashes with this panic after a few min of playing.

Do you have any specifics about this issue? Can you reproduce it successfully? The crash is happening from inside of the incoming audio handler, meaning it's triggered by other users talking in the channel.

**Comment by caindrac** [comment] 2016-07-11 15:45
It is a not a problem to reproduce it happens every time I turn on the bot. It has happened both after starting a song as well as just sitting afk for a 1-2 minutes.

**Comment by bontibon** [comment] 2016-07-11 15:47
> It has happened both after starting a song as well as just sitting afk for a 1-2 minutes.

But were any users on the server talking? What versions of Mumble are the talking users using?

**Comment by caindrac** [comment] 2016-07-11 15:49
Yes there where people talking I don't have the information on my on what version they are using.

**Comment by matthieugrieger** [comment] 2016-07-11 19:19
You can check what version they are using by right-clicking on them and selecting "Information". They do have to be online, however.

**Comment by bontibon** [comment] 2016-07-11 22:20
@matthieugrieger Just pushed layeh/gumble@f0a4a299 which may fix the issue.

**Comment by matthieugrieger** [comment] 2016-07-11 22:59
@bontibon: Thanks, I'll update the vendored dependencies.

**Comment by matthieugrieger** [comment] 2016-07-11 23:06
@caindrac: Could you try out the newest release and let us know if you still experience this issue?

**Comment by matthieugrieger** [comment] 2016-07-13 18:25
Closing this issue as the latest update most likely fixed it. @caindrac, if you continue to have problems, please let me know.

**Closed by matthieugrieger** 2016-07-13 18:25 UTC
Labels: bug
