### ISSUE TITLE
Running on a Rasperry Pi

### ISSUE THREAD

**Issue by Vectri** [matthieugrieger/mumbledj#124] opened 2016-02-19 04:17 UTC
Hello. I'm trying to run this on a raspberry pi and have been receiving errors on running `make`. At first I received errors regarding the opus path file, something like 'the directory containing opus.pc is not defined. You may want to define this in PKG_CONFIG_PATH'. After updating opus not through apt-get and through manual means, I now have this error:

```
can't load package: package github.com/golang/protobuf: no buildable Go source files in /home/pi/mumbledj-2.8.15/.vendor/src/github.com/golang/protobuf
WORK=/tmp/go-build550908990
can't load package: package github.com/timshannon/go-openal: no buildable Go source files in /home/pi/mumbledj-2.8.15/.vendor/src/github.com/timshannon/go-openal
=> Done!
goop go build
# _/home/pi/mumbledj-2.8.15
./cache.go:85: syntax error: unexpected range, expecting {
./cache.go:100: syntax error: unexpected }
goop: Command failed with exit status 2
Makefile:4: recipe for target 'mumbledj' failed
make: *** [mumbledj] Error 2
```

I would assume it's possible to run this on Raspbian. Any help?

**Comment by matthieugrieger** [comment] 2016-02-19 07:37
I believe this is a weird issue with the paths to the Go source files being incorrect.

Try creating a symbolic link between `/home/pi/mumbledj-2.8.15/.vendor/src/github.com/golang/protobuf` and `/home/pi/mumbledj-2.8.15/.vendor/src/github.com/golang/protobuf/proto`, and another symbolic link between `/home/pi/mumbledj-2.8.15/.vendor/src/github.com/timshannon/go-openal` and `/home/pi/mumbledj-2.8.15/.vendor/src/github.com/timshannon/go-openal/openal`.

I think this issue comes up when the Go source code for the dependencies is not in the root of the repository. If you look at the [protobuf repo](https://github.com/golang/protobuf) the code is within the `proto` directory, for example.

**Comment by Vectri** [comment] 2016-02-20 02:00
An error is still being thrown after I use the `make`:

`can't load package: package github.com/golang/protobuf: no buildable Go source files in /home/pi/mumbledj-2.8.15/.vendor/src/github.com/golang/protobuf`

and further down

```
# _/home/pi/mumbledj-2.8.15
./cache.go:85: syntax error: unexpected range, expecting {
./cache.go:100: syntax error: unexpected }
goop: Command failed with exit status 2
Makefile:4: recipe for target 'mumbledj' failed
make: *** [mumbledj] Error 2
```

**Comment by matthieugrieger** [comment] 2016-02-20 03:52
Did you create a symbolic link for `github.com/golang/protobuf` as shown above?

**Comment by Vectri** [comment] 2016-02-20 04:51
I did. Should it not be producing that error?

**Comment by matthieugrieger** [comment] 2016-02-20 09:00
The other person who had this issue never really responded to tell me how their issue was resolved, so I'm not quite sure. In my mind I feel like it should fix it since the error message states that it is still searching in the wrong directory for buildable Go files. Maybe verify to make sure that the symbolic link is correct/working?

**Comment by Vectri** [comment] 2016-02-20 23:42
After attempting the links again, nothing has changed. I checked whether the symbolic links were working, and I'm sure they are. I'll have to see if I can fix it if ever. Thank you for the help, though. :)

**Comment by matthieugrieger** [comment] 2016-02-20 23:58
Ah, strange. Thanks for checking.

I will look around when I get the chance and see if I can dig up anything.

**Comment by mikolan** [comment] 2016-03-27 19:09
Seems to go wrong when goop is resolving dependencies. Try adding the problematic repos to the Goopfile.

**Comment by Redyz** [comment] 2016-04-16 05:14
I too had all those problems, I've managed to fix them by appending 
`
github.com/timshannon/go-openal                                                                                                                                                                                                                                                  
github.com/golang/protobuf
`

To the Goopfile, and removing the bits and pieces of the Cache code both in cache.go and main.go. I'm totally new to Go but it seems there were errors in Cache.go.

Anyway it now compiles again.

**Comment by Vectri** [comment] 2016-04-24 01:34
Can you tell me what exactly you removed from cache.go and main.go?

**Comment by Redyz** [comment] 2016-04-24 01:38
Sure thing, I've modified my local copy a bit so hopefully this is just the baseline to make it work:
**main.go**
Simply commented this bit out since it deals with the cache
`//go dj.cache.ClearExpired()`

**cache.go**
Commented any function that dealt with cache
`
func (c *SongCache) ClearExpired() 
func (c *SongCache) ClearOldest()
`

And along with
`//if err := c.ClearOldest(); err != nil {
                       //break
 //}
`

I then removed any errors caused by unused variables or includes and it ended up running.

Hopefully the format of this post isn't too messed up.

**Comment by Vectri** [comment] 2016-04-24 03:01
It worked and I'm so thankful for your help

**Comment by Redyz** [comment] 2016-04-24 03:03
No problem! I'm not sure if I'm setting the build wrong or the project simply doesn't build anymore but yeah, happy hacking

**Comment by matthieugrieger** [comment] 2016-04-24 04:02
What version of Go are you two using? I've never had any issues with compiling the cache portion of the code.

**Comment by Redyz** [comment] 2016-04-24 04:05
I'm not familiar with go, but I'm guessing this is what you are asking for:
`goop go version`
`go version go1.3.3 linux/amd64`

**Comment by Vectri** [comment] 2016-04-24 05:09
The raspberry pi comes with 1.3.3 and it's pretty difficult to upgrade, at least as far as my attempts went.

**Comment by matthieugrieger** [comment] 2016-04-24 05:29
Ah, that makes sense then. I generally develop the bot for the newest Go release. I'll have to look into getting this thing to work correctly with the Raspberry Pi as it's pretty fussy.

**Comment by matthieugrieger** [comment] 2016-04-24 07:50
@Redyz, @Vectri: You may want to take a look at this: http://dave.cheney.net/2015/09/04/building-go-1-5-on-the-raspberry-pi

**Comment by Redyz** [comment] 2016-04-24 15:08
I have to say that whilst my mumble server is running on a pi, I was compiling the bot on another machine.

`Linux hostname 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u2 (2016-01-02) x86_64 GNU/Linux`

Maybe I didn't set up my go version properly? It may just be an issue with an old version of go then.

**Comment by Vectri** [comment] 2016-04-24 15:57
I've tried using chaney's solution and it gave me errors   installing it. From what I've read, the errors I was getting when running make on mumbledj were related to the outdated version of Go

**Comment by matthieugrieger** [comment] 2016-06-21 06:24
Go 1.5 or greater is now required for MumbleDJ. I recommend using https://github.com/moovweb/gvm to install newer versions of Go if they are not distributed via the distro repos.

**Closed by matthieugrieger** 2016-06-21 06:24 UTC
Labels: setup help
