### ISSUE TITLE
Request for !help enhancement

### ISSUE THREAD

**Issue by raz0rsdge** [matthieugrieger/mumbledj#96] opened 2015-10-31 18:29 UTC
As users requested I've changed some shortcuts for commanding our bot and this is what I think might be improved:

1. If you change some command aliases via config (maybe !a for add instead of !add) it will not be recognized by the !help output, !help output never shows this

2. fact 1. can't be ignored due to deletion of the origin command instead of adding another alias to the default, so I would suggest a merge with existing default (!a && !add)

Sry for bad language - hope I've explained the request for enhancement...

**Comment by matthieugrieger** [comment] 2015-11-01 00:31
This is something that I am hoping to address in the refactor that I am currently working on. Hopefully I get some time fairly soon to work on it. The help command would dynamically generate the HTML it outputs, replacing the default aliases with the current aliases set in configuration.

I'm closing this issue as it appears to be a duplicate of https://github.com/matthieugrieger/mumbledj/issues/63. If it isn't, let me know!

**Closed by matthieugrieger** 2015-11-01 00:31 UTC

**Comment by raz0rsdge** [comment] 2015-11-01 09:40
You are right, didn't read this - my fault!
